pull_request_rules:
  - name: Auto-merge Renovate
    conditions:
      - author=renovate[bot]
      - base=main
      - "-merged"
      - "-conflict"
    actions:
      merge:
        method: rebase
  - name: Auto-merge Dependabot
    conditions:
      - author=dependabot[bot]
      - base=main
      - "-merged"
      - "-conflict"
    actions:
      merge:
        method: rebase